# Generated by Django 6.0.2 on 2026-03-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWeatherStats',
            fields=[
                ('record_date', models.DateTimeField(primary_key=True, serialize=False)),
                ('max_temp', models.FloatField(blank=True, null=True)),
                ('min_temp', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daily_weather_stats',
                'managed': True,
            },
        ),
    ]
